import {OnekitPage} from '../toutiao2weixin/index';
import {tt} from '../toutiao2weixin/index';
OnekitPage({
    data:{
        icons:[
            [
                'success',
                'success_no_circle'
            ],
            [
                'info',
                'warn'
            ],
            [
                'waiting',
                'clear'
            ],
            [
                'cancel',
                'download'
            ],
            [
                'search'
            ]
        ],
        sizes:[
            66,
            48,
            36,
            24
        ],
        colors:[
            '#222222',
            '#CACACA',
            '',
            '#50ABF9'
        ]
    }
});
