import OnekitPage from '../toutiao2weixin/OnekitPage';

OnekitPage({
    data:{
        icons:[
            [
                'success',
                'success_no_circle'
            ],
            [
                'info',
                'warn'
            ],
            [
                'waiting',
                'clear'
            ],
            [
                'cancel',
                'download'
            ],
            [
                'search'
            ]
        ],
        sizes:[
            68,
            50,
            44
        ],
        colors:[
            '#222222',
            '#CACACA',
            '',
            '#50ABF9'
        ]
    }
});